spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices-realm
  datasource:
    url: jdbc:postgresql://localhost:5432/AuthServiceDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
keycloak:
  realm: microservices-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: spring-microservices
  credentials:
    secret: oYVcSzV9bwKd95VfsV0zEhqlSzTbFyqD
  use-resource-role-mappings: true
  bearer-only: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8070/eureka
server:
  port: 8181