spring:
  cloud:
    gateway:
      lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/order/**
keycloak:
  realm: microservices-realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: spring-microservices
  credentials:
    secret: oYVcSzV9bwKd95VfsV0zEhqlSzTbFyqD
  use-resource-role-mappings: true
  bearer-only: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8070/eureka
server:
  port: 8072