spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/microservices-realm
      client:
        registration:
          keycloak:
            client-id: spring-microservices
            client-secret: UwW3MThVtBFS1ujL5Zmy6PyOVIv9XHou
            authorization-grant-type: authorization_code
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/microservices-realm
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/order/**
        - id: createUser-service
          uri: lb://createUser-service/
          predicates:
            - Path=/createUser/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8070/eureka
server:
  port: 8072
logging:
  level:
    org.springframework.security: DEBUG