spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/HistoryServiceDB
      uuid-representation: standard
      auto-index-creation: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices-realm
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: history-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: "com.utochkin.orderservice.dto.OrderDtoForKafka:com.utochkin.historyservice.dto.OrderDtoForKafka"
        spring.json.trusted.packages: "com.utochkin.orderservice.dto,com.utochkin.historyservice.dto"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8070/eureka
server:
  port: 8184