# для локального запуска
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/microservices-realm
#  cloud:
#    openfeign:
#      oauth2:
#        enabled: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/PaymentServiceDB
#    username: postgres
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: Europe/Moscow
#  liquibase:
#    change-log: classpath:changelog/db.changelog-master.yaml
#    enabled: true
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      register-with-eureka: true
#      fetch-registry: true
#      defaultZone: http://localhost:8070/eureka
#server:
#  port: 8182

spring:
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices-realm
  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      oauth2:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/PaymentServiceDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
  liquibase:
    change-log: classpath:changelog/db.changelog-master.yaml
    enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry:    true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8182
management:
  tracing:
    sampling:
      probability: 0.1
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,trace
  endpoint:
    prometheus:
      access: unrestricted
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
logging:
  level:
    root: INFO
  logstash:
    host: logstash
    port: 5000