spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8070/eureka
keycloak:
  auth-server-url: http://localhost:8080
  realm: microservices-realm
  client-id: spring-microservices
  client-secret: apIkjKljSVdsDtzUknhm8AKIFECM2AfX
server:
  port: 8182
  servlet:
    session:
      cookie:
        same-site: lax
logging:
  level:
    org.springframework.security: TRACE