spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices-realm
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8070/eureka
keycloak:
  auth-server-url: http://localhost:8080
  realm: microservices-realm
  client-id: spring-microservices
  client-secret: UwW3MThVtBFS1ujL5Zmy6PyOVIv9XHou
server:
  port: 8182